version: '3.9'

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ltm20212
      - MYSQL_PASSWORD=ltm20212
      - MYSQL_USER=ltm20212
      - MYSQL_DATABASE=ltm20212